"""make_data.py -- copy the current TOMS event data next to the mockups and rebuild data.js from it.

Run from anywhere:  python docs/event_editor/mockups/make_data.py
It copies (never modifies) these files into data_snapshot/, then writes data.js for the HTML pages:
    assets/data/events/pool_*.json
    assets/data/story/floors/F??.json      (the floor specs only; F??.stage.json grids are skipped)
    assets/data/text.json                  (only the keys events use, to keep the copy small)
"""
import datetime
import glob
import json
import os
import shutil

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, '..', '..', '..'))
DATA = os.path.join(ROOT, 'assets', 'data')
SNAP = os.path.join(HERE, 'data_snapshot')


def load(p):
    with open(p, encoding='utf8') as f:
        return json.load(f)


def main():
    if os.path.isdir(SNAP):
        shutil.rmtree(SNAP)
    os.makedirs(os.path.join(SNAP, 'events'))
    os.makedirs(os.path.join(SNAP, 'floors'))

    pools, events = [], []
    for p in sorted(glob.glob(os.path.join(DATA, 'events', 'pool_*.json'))):
        shutil.copy2(p, os.path.join(SNAP, 'events'))
        pid = os.path.basename(p)[:-5]
        pools.append(pid)
        for e in load(p)['events']:
            events.append({'id': e['eventId'], 'kind': e['kind'], 'pool': pid, 'text': e['text']})

    floors = []
    for p in sorted(glob.glob(os.path.join(DATA, 'story', 'floors', 'F??.json'))):
        shutil.copy2(p, os.path.join(SNAP, 'floors'))
        d = load(p)
        floors.append({'id': d['id'], 'act': d['act'], 'events': list(d.get('events', []))})

    # text: the keys events point at, plus the placeholder keys of ids floors use but no pool defines
    strings = load(os.path.join(DATA, 'text.json'))['strings']
    known = {e['id'] for e in events}
    wanted = {e['text'] for e in events} | {i for f in floors for i in f['events'] if i not in known}
    texts = {k: strings[k] for k in sorted(wanted) if k in strings}
    with open(os.path.join(SNAP, 'text_events.json'), 'w', encoding='utf8') as f:
        json.dump({'_comment': 'Event strings copied from assets/data/text.json', 'strings': texts}, f, ensure_ascii=False, indent=2)

    stamp = datetime.date.today().isoformat()
    out = {'snapshot': stamp, 'pools': pools, 'events': events, 'floors': floors, 'texts': texts}
    with open(os.path.join(HERE, 'data.js'), 'w', encoding='utf8') as f:
        f.write(f'// Generated by make_data.py from assets/data on {stamp}. A copy for the mockups; the game never reads it.\n')
        f.write('const DATA = ' + json.dumps(out, ensure_ascii=False) + ';\n')
        f.write(LEGACY)
    print(f'{len(pools)} pools, {len(events)} events, {len(floors)} floors, {len(texts)} text keys -> data_snapshot/, data.js')


# The first three mockups read e.str and DATA.problems; derive them here so data.js stays the one source.
LEGACY = r"""
(() => {
  const T = DATA.texts, ids = new Set(DATA.events.map(e => e.id)), used = new Set(DATA.floors.flatMap(f => f.events));
  DATA.events.forEach(e => { const s = T[e.text] || {}; e.str = Object.fromEntries(Object.entries(s).filter(([k]) => !k.startsWith('_'))); });
  DATA.problems = [
    ...DATA.events.filter(e => !used.has(e.id)).map(e => ({ rule: 'orphan', id: e.id, where: e.pool + '.json', detail: 'no floor references this event' })),
    ...DATA.floors.flatMap(f => f.events.filter(i => !ids.has(i)).map(i => ({ rule: 'missing_event', id: i, where: f.id + '.json', detail: f.id + ' (' + f.act + ') references an event id that no pool defines' }))),
    ...DATA.events.filter(e => !T[e.text]).map(e => ({ rule: 'missing_text', id: e.text, where: 'text.json', detail: 'no string in text.json for this key' })),
    ...DATA.events.filter(e => { const v = Object.values(e.str); return v.length && new Set(v).size === 1; }).map(e => ({ rule: 'untranslated', id: e.text, where: 'text.json', detail: 'every language has the same string' })),
  ];
})();
"""

if __name__ == '__main__':
    main()
