"""make_bundle.py -- copy what the HTML stage editor needs from assets/data into stage_bundle.js.

Run from anywhere:  python tools/web_editors/make_bundle.py
Reads (never writes) assets/data:
    story/floors/F??.json         floor specs (events a floor can roll, nextFloor, handAuthoredStage, ...)
    story/floors/F??.stage.json   the generated grids; boss floors use stages/<handAuthoredStage> instead
    events/pool_*.json            every defined event (id, kind, pool, text key)
    text.json                     only the event strings
    enemies.json, items.json, footprints.json, media/sprites/manifest.json
The page works from this copy; "Open project folder" in the page reads and writes the real files instead.
"""
import datetime
import glob
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, '..', '..'))
DATA = os.path.join(ROOT, 'assets', 'data')


def load(path):
    """The parsed JSON, plus how the file ends its lines, so a save can write it back byte-compatible."""
    with open(path, 'rb') as f:
        raw = f.read()
    return json.loads(raw.decode('utf8')), {'crlf': b'\r\n' in raw, 'finalNewline': raw.endswith(b'\n')}


def rel(path):
    return os.path.relpath(path, ROOT).replace('\\', '/')


def main():
    floors = []
    for spec_path in sorted((p for p in glob.glob(os.path.join(DATA, 'story', 'floors', '*.json')) if not p.endswith('.stage.json'))):
        spec, spec_eol = load(spec_path)
        hand = spec.get('handAuthoredStage')
        stage_path = os.path.join(DATA, 'stages', hand) if hand else spec_path[:-5] + '.stage.json'
        if not os.path.exists(stage_path):
            continue
        stage, stage_eol = load(stage_path)
        floors.append({'id': spec['id'], 'specPath': rel(spec_path), 'spec': spec, 'specEol': spec_eol,
                       'stagePath': rel(stage_path), 'stage': stage, 'stageEol': stage_eol})

    events = []
    for p in sorted(glob.glob(os.path.join(DATA, 'events', 'pool_*.json'))):
        pool = os.path.basename(p)[:-5]
        for e in load(p)[0]['events']:
            rec = {'id': e['eventId'], 'kind': e['kind'], 'pool': pool, 'text': e['text']}
            for k in ('trigger', 'requires', 'actions', 'next'):   # event logic, docs/event_editor/06_EVENT_LOGIC.md
                if k in e:
                    rec[k] = e[k]
            events.append(rec)

    strings = load(os.path.join(DATA, 'text.json'))[0]['strings']
    used = {e['text'] for e in events} | {i for f in floors for i in f['spec'].get('events', [])}
    texts = {k: {l: strings[k].get(l) for l in ('zh_TW', 'en')} for k in sorted(used) if k in strings}

    pick = lambda d: {l: d.get(l) for l in ('zh_TW', 'en')} if isinstance(d, dict) else d
    enemies = {k: {'name': pick(v.get('name')), 'hp': v.get('hp'), 'atk': v.get('atk'), 'def': v.get('def')}
               for k, v in load(os.path.join(DATA, 'enemies.json'))[0].items() if not k.startswith('_')}
    items = {k: {'name': pick(v.get('name')), 'effect': v.get('effect')}
             for k, v in load(os.path.join(DATA, 'items.json'))[0].items() if not k.startswith('_')}
    footprints = {k: v for k, v in load(os.path.join(DATA, 'footprints.json'))[0].items() if not k.startswith('_')}
    sprites = load(os.path.join(ROOT, 'assets', 'media', 'sprites', 'manifest.json'))[0]['sprites']
    kp = os.path.join(DATA, 'events', 'kinds.json')
    kinds = {k: v for k, v in load(kp)[0].items() if not k.startswith('_')} if os.path.exists(kp) else {}

    stamp = datetime.date.today().isoformat()
    bundle = {'snapshot': stamp, 'floors': floors, 'events': events, 'texts': texts,
              'enemies': enemies, 'items': items, 'footprints': footprints, 'sprites': sprites, 'kinds': kinds}
    out = os.path.join(HERE, 'stage_bundle.js')
    with open(out, 'w', encoding='utf8') as f:
        f.write(f'// Generated by make_bundle.py from assets/data on {stamp}. A read-only copy for stage_editor.html.\n')
        f.write('const BUNDLE = ' + json.dumps(bundle, ensure_ascii=False) + ';\n')
    print(f'{len(floors)} floors, {len(events)} events, {len(enemies)} enemies, {len(items)} items -> {rel(out)}')


if __name__ == '__main__':
    main()
