"""make_data.py -- copy the current TOMS event data next to the HTML editors and rebuild data.js from it.

Run from anywhere:  python tools/web_editors/make_data.py
It copies (never modifies) these files into data_snapshot/, then writes data.js for the HTML pages:
    assets/data/events/pool_*.json
    assets/data/story/floors/F??.json      (the floor specs only; F??.stage.json grids are skipped)
    assets/data/text.json                  (only the keys events use, to keep the copy small)
"""
import datetime
import glob
import json
import os
import shutil

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, '..', '..'))
DATA = os.path.join(ROOT, 'assets', 'data')
SNAP = os.path.join(HERE, 'data_snapshot')


def load(p):
    with open(p, encoding='utf8') as f:
        return json.load(f)


def main():
    if os.path.isdir(SNAP):
        shutil.rmtree(SNAP)
    os.makedirs(os.path.join(SNAP, 'events'))
    os.makedirs(os.path.join(SNAP, 'floors'))

    pools, events = [], []
    for p in sorted(glob.glob(os.path.join(DATA, 'events', 'pool_*.json'))):
        shutil.copy2(p, os.path.join(SNAP, 'events'))
        pid = os.path.basename(p)[:-5]
        pools.append(pid)
        for e in load(p)['events']:
            rec = {'id': e['eventId'], 'kind': e['kind'], 'pool': pid, 'text': e['text']}
            for k in ('trigger', 'requires', 'actions', 'next', 'once'):   # event logic, docs/event_editor/06_EVENT_LOGIC.md
                if k in e:
                    rec[k] = e[k]
            events.append(rec)

    floors = []
    for p in sorted(glob.glob(os.path.join(DATA, 'story', 'floors', 'F??.json'))):
        shutil.copy2(p, os.path.join(SNAP, 'floors'))
        d = load(p)
        rec = {'id': d['id'], 'act': d['act'], 'role': d.get('role', 'normal'), 'events': list(d.get('events', [])),
               'next': d.get('nextFloor')}
        if isinstance(d.get('stairs'), list):   # docs/event_editor/05_FLOOR_LINKS.md; absent = derived from nextFloor
            rec['stairs'] = d['stairs']
        floors.append(rec)

    # text: the keys events point at, plus the placeholder keys of ids floors use but no pool defines
    strings = load(os.path.join(DATA, 'text.json'))['strings']
    known = {e['id'] for e in events}
    wanted = {e['text'] for e in events} | {i for f in floors for i in f['events'] if i not in known}
    texts = {k: strings[k] for k in sorted(wanted) if k in strings}
    with open(os.path.join(SNAP, 'text_events.json'), 'w', encoding='utf8') as f:
        json.dump({'_comment': 'Event strings copied from assets/data/text.json', 'strings': texts}, f, ensure_ascii=False, indent=2)

    # who can be talked to, and where: npc ids placed on each floor's grid (boss floors use stages/<handAuthoredStage>)
    npcs = {}
    for spec_path in sorted(glob.glob(os.path.join(DATA, 'story', 'floors', 'F??.json'))):
        spec = load(spec_path)
        hand = spec.get('handAuthoredStage')
        grid = os.path.join(DATA, 'stages', hand) if hand else spec_path[:-5] + '.stage.json'
        if not os.path.exists(grid):
            continue
        st = load(grid)
        cells = ''.join(st.get('tiles', []))
        for ch, sem in st.get('legend', {}).items():
            if sem.startswith('npc:') and ch in cells:
                npcs.setdefault(sem[4:], []).append(spec['id'])

    # variables an event can read or write: the story's flags and counters, plus event variables (vars.json, optional)
    story = os.path.join(DATA, 'story')
    flags = {k: v for k, v in load(os.path.join(story, 'flags.json')).items() if not k.startswith('_')}        # full records, editable in the value tabs
    counters = {k: v for k, v in load(os.path.join(story, 'counters.json')).items() if not k.startswith('_')}
    vars_path = os.path.join(story, 'vars.json')
    evars = {k: v for k, v in load(vars_path).items() if not k.startswith('_')} if os.path.exists(vars_path) else {}

    kinds_path = os.path.join(DATA, 'events', 'kinds.json')   # event kinds (written by the event editor's Kinds tab)
    kinds = {k: v for k, v in load(kinds_path).items() if not k.startswith('_')} if os.path.exists(kinds_path) else {}

    stamp = datetime.date.today().isoformat()
    out = {'snapshot': stamp, 'pools': pools, 'events': events, 'floors': floors, 'texts': texts,
           'npcs': npcs, 'flags': flags, 'counters': counters, 'vars': evars, 'kinds': kinds}
    with open(os.path.join(HERE, 'data.js'), 'w', encoding='utf8') as f:
        f.write(f'// Generated by make_data.py from assets/data on {stamp}. A copy for the HTML editors; the game never reads it.\n')
        f.write('const DATA = ' + json.dumps(out, ensure_ascii=False) + ';\n')
    print(f'{len(pools)} pools, {len(events)} events, {len(floors)} floors, {len(texts)} text keys -> data_snapshot/, data.js')



if __name__ == '__main__':
    main()
