// embedded_shaders.cpp -- see embedded_shaders.h. The included headers are generated by
// bgfx_compile_shaders(... AS_HEADERS) in engine/CMakeLists.txt, one folder per profile.
#include "embedded_shaders.h"
#include <cstdio>

// Web: only ESSL (WebGL2). Android: ESSL (GLES3) + SPIR-V (Vulkan). Desktop: all four.
#if !defined(__EMSCRIPTEN__) && !defined(__ANDROID__)
#define TOMS_SHADERS_DESKTOP 1
#include "dxbc/vs_sprite.sc.bin.h"
#include "dxbc/fs_sprite.sc.bin.h"
#include "dxbc/vs_imgui.sc.bin.h"
#include "dxbc/fs_imgui.sc.bin.h"
#include "dxbc/vs_rml.sc.bin.h"
#include "glsl/vs_sprite.sc.bin.h"
#include "glsl/fs_sprite.sc.bin.h"
#include "glsl/vs_imgui.sc.bin.h"
#include "glsl/fs_imgui.sc.bin.h"
#include "glsl/vs_rml.sc.bin.h"
#endif
#ifndef __EMSCRIPTEN__
#include "spirv/vs_sprite.sc.bin.h"
#include "spirv/fs_sprite.sc.bin.h"
#include "spirv/vs_imgui.sc.bin.h"
#include "spirv/fs_imgui.sc.bin.h"
#include "spirv/vs_rml.sc.bin.h"
#endif
#include "essl/vs_sprite.sc.bin.h"
#include "essl/fs_sprite.sc.bin.h"
#include "essl/vs_imgui.sc.bin.h"
#include "essl/fs_imgui.sc.bin.h"
#include "essl/vs_rml.sc.bin.h"

namespace toms::next {
namespace {

struct Blob { const uint8_t* data; uint32_t size; };

#define TOMS_BLOB(name) Blob{ name, (uint32_t)sizeof(name) }

struct ProgramBlobs { Blob vs, fs; };

// One profile's three programs. RmlUi reuses the ImGui fragment shader (texture * colour).
#define TOMS_PROGRAMS(ext)                                                                          \
    switch (which) {                                                                                \
    case ShaderProgram::Sprite: out = { TOMS_BLOB(vs_sprite_##ext), TOMS_BLOB(fs_sprite_##ext) }; break; \
    case ShaderProgram::ImGui:  out = { TOMS_BLOB(vs_imgui_##ext),  TOMS_BLOB(fs_imgui_##ext) };  break; \
    case ShaderProgram::RmlUi:  out = { TOMS_BLOB(vs_rml_##ext),    TOMS_BLOB(fs_imgui_##ext) };  break; \
    }                                                                                               \
    return true

bool pick(ShaderProgram which, bgfx::RendererType::Enum type, ProgramBlobs& out) {
    switch (type) {
#ifdef TOMS_SHADERS_DESKTOP
    case bgfx::RendererType::Direct3D11:
    case bgfx::RendererType::Direct3D12:   // bgfx's D3D12 backend accepts DXBC (shader model 5)
        TOMS_PROGRAMS(dxbc);
    case bgfx::RendererType::OpenGL:
        TOMS_PROGRAMS(glsl);
#endif
#ifndef __EMSCRIPTEN__
    case bgfx::RendererType::Vulkan:
        TOMS_PROGRAMS(spv);
#endif
    case bgfx::RendererType::OpenGLES:     // also the web build (bgfx's WebGL2 backend reports GLES)
        TOMS_PROGRAMS(essl);
    default:
        return false;
    }
}

}  // namespace

bgfx::ProgramHandle createEmbeddedProgram(ShaderProgram which) {
    ProgramBlobs b{};
    if (!pick(which, bgfx::getRendererType(), b)) {
        std::fprintf(stderr, "[toms] no embedded shaders for renderer '%s'\n",
                     bgfx::getRendererName(bgfx::getRendererType()));
        return BGFX_INVALID_HANDLE;
    }
    bgfx::ShaderHandle vs = bgfx::createShader(bgfx::makeRef(b.vs.data, b.vs.size));
    bgfx::ShaderHandle fs = bgfx::createShader(bgfx::makeRef(b.fs.data, b.fs.size));
    return bgfx::createProgram(vs, fs, true /* destroy shaders with the program */);
}

}  // namespace toms::next
