// embedded_shaders.cpp -- see embedded_shaders.h. The included headers are generated by
// bgfx_compile_shaders(... AS_HEADERS) in engine/CMakeLists.txt, one folder per profile.
#include "embedded_shaders.h"
#include <cstdio>

#include "dxbc/vs_sprite.sc.bin.h"
#include "dxbc/fs_sprite.sc.bin.h"
#include "dxbc/vs_imgui.sc.bin.h"
#include "dxbc/fs_imgui.sc.bin.h"
#include "spirv/vs_sprite.sc.bin.h"
#include "spirv/fs_sprite.sc.bin.h"
#include "spirv/vs_imgui.sc.bin.h"
#include "spirv/fs_imgui.sc.bin.h"
#include "glsl/vs_sprite.sc.bin.h"
#include "glsl/fs_sprite.sc.bin.h"
#include "glsl/vs_imgui.sc.bin.h"
#include "glsl/fs_imgui.sc.bin.h"
#include "essl/vs_sprite.sc.bin.h"
#include "essl/fs_sprite.sc.bin.h"
#include "essl/vs_imgui.sc.bin.h"
#include "essl/fs_imgui.sc.bin.h"

namespace toms::next {
namespace {

struct Blob { const uint8_t* data; uint32_t size; };

#define TOMS_BLOB(name) Blob{ name, (uint32_t)sizeof(name) }

struct ProgramBlobs { Blob vs, fs; };

bool pick(ShaderProgram which, bgfx::RendererType::Enum type, ProgramBlobs& out) {
    const bool sprite = which == ShaderProgram::Sprite;
    switch (type) {
    case bgfx::RendererType::Direct3D11:
    case bgfx::RendererType::Direct3D12:   // bgfx's D3D12 backend accepts DXBC (shader model 5)
        out = sprite ? ProgramBlobs{ TOMS_BLOB(vs_sprite_dxbc), TOMS_BLOB(fs_sprite_dxbc) }
                     : ProgramBlobs{ TOMS_BLOB(vs_imgui_dxbc),  TOMS_BLOB(fs_imgui_dxbc) };
        return true;
    case bgfx::RendererType::Vulkan:
        out = sprite ? ProgramBlobs{ TOMS_BLOB(vs_sprite_spv), TOMS_BLOB(fs_sprite_spv) }
                     : ProgramBlobs{ TOMS_BLOB(vs_imgui_spv),  TOMS_BLOB(fs_imgui_spv) };
        return true;
    case bgfx::RendererType::OpenGL:
        out = sprite ? ProgramBlobs{ TOMS_BLOB(vs_sprite_glsl), TOMS_BLOB(fs_sprite_glsl) }
                     : ProgramBlobs{ TOMS_BLOB(vs_imgui_glsl),  TOMS_BLOB(fs_imgui_glsl) };
        return true;
    case bgfx::RendererType::OpenGLES:     // also what the future WebGL2 build uses
        out = sprite ? ProgramBlobs{ TOMS_BLOB(vs_sprite_essl), TOMS_BLOB(fs_sprite_essl) }
                     : ProgramBlobs{ TOMS_BLOB(vs_imgui_essl),  TOMS_BLOB(fs_imgui_essl) };
        return true;
    default:
        return false;
    }
}

}  // namespace

bgfx::ProgramHandle createEmbeddedProgram(ShaderProgram which) {
    ProgramBlobs b{};
    if (!pick(which, bgfx::getRendererType(), b)) {
        std::fprintf(stderr, "[toms] no embedded shaders for renderer '%s'\n",
                     bgfx::getRendererName(bgfx::getRendererType()));
        return BGFX_INVALID_HANDLE;
    }
    bgfx::ShaderHandle vs = bgfx::createShader(bgfx::makeRef(b.vs.data, b.vs.size));
    bgfx::ShaderHandle fs = bgfx::createShader(bgfx::makeRef(b.fs.data, b.fs.size));
    return bgfx::createProgram(vs, fs, true /* destroy shaders with the program */);
}

}  // namespace toms::next
